### ISSUE TITLE
Lacking control of dirb scan if the scan takes a turn down a bad dir path

### ISSUE THREAD

**Issue by claudijd** [mozilla/vautomator-standalone#9]
dirb supports the ability to skip or quit if you see the scan going down say a /docs path and bruting that out.  In the current implementation, you don't have visibility into what's happening there, nor do  you have the ability to affect it's depth.  Perhaps this is something we'd simply prefer to set directly in the scan to avoid such problems and make the run time a bit more sane.

**Comment by caggle** [comment]
Currently I am running dirb with these flags: `-f -w -S -r` as can be seen in https://github.com/caggle/vautomator-standalone/blob/master/lib/task.py#L342.

These flags mean:
- Fine tuning of "not found" response (-f)
- Silent mode (-S)
- Don't search recursively (-r)
- Don't stop on warning messages (-w)

I have specified some of these on purpose, so the tool can be "run and forgotten". I understand some sites may take a long time, but this combination of flags I found is the most straightforward to get meaningful results (obviously this also depends on the size of the wordlist). Disabling recursive scan seems to take care of the tool going down a rabbit hole in particular.

You are right in saying we don't have the ability to affect depth (I think that's another flag to dirb), and currently the wordlist is hardcoded; perhaps a better way to address this issue is to implement command line flags to vautomator which would include these options? (see issue https://github.com/caggle/vautomator-standalone/issues/7)

**Comment by gdestuynder** [comment]
on master atm mine seems to never end on some sites:

```
[4a584eac48cb] 2019-02-12 08:18:21 PM UTC INFO     [+] Running dirb scan...

^CTraceback (most recent call last):
  File "./run.py", line 114, in <module>
    main()
  File "./run.py", line 110, in main
    runVA(va_scan, output_path)
  File "./run.py", line 74, in runVA
    results = scan_with_tasks.runTasks()
  File "/app/vautomator/lib/target.py", line 147, in runTasks
    dirbrute_results = one_task.runDirectoryBruteScan()
  File "/app/vautomator/lib/task.py", line 350, in runDirectoryBruteScan
    p.wait()
  File "/usr/lib/python3.5/subprocess.py", line 1389, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.5/subprocess.py", line 1339, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

~/git/infosec/vautomator-standalone master 1h 55m 32s
```
(i killed it after 2h)

**Comment by caggle** [comment]
I believe this PR: https://github.com/mozilla/vautomator-standalone/pull/22 fixed it, for `dirb` scans only at least.
We should still apply the same principle to other scans (i.e. timeout & kill after a set time).
